export enum ConversationState {
  MAIN_MENU = 'MAIN_MENU',

  POLICY_MENU = 'POLICY_MENU',
  LEAVE_MENU = 'LEAVE_MENU',
  BENEFITS_MENU = 'BENEFITS_MENU',
  VERIFICATION_MENU = 'VERIFICATION_MENU',

  ESCALATION = 'ESCALATION',
}
