export enum ConversationState {
  MAIN_MENU = 'MAIN_MENU',

  POLICY_MENU = 'POLICY_MENU',
  LEAVE_MENU = 'LEAVE_MENU',
  BENEFITS_MENU = 'BENEFITS_MENU',
  VERIFICATION_MENU = 'VERIFICATION_MENU',
  DOCUMENT_REQUEST_MENU = 'DOCUMENT_REQUEST_MENU',
  HR_MESSAGE = 'HR_MESSAGE',
  HR_QUEUE = 'HR_QUEUE',

  ESCALATION = 'ESCALATION',
}
